[project]
name = "ivaldi"
version = "0.3.5"
description = "Create a portable version of your Python Project"
authors = [
    {name = "Fionn Tolster (@FionnT)"}
]
license = "MIT"
license-files = ["LICENSE", "THIRD_PARTY_NOTICES.md"]
readme = "README.md"
requires-python = ">3.10"
dependencies = [
  "requests (>=2.34.2,<3.0.0)", 
  "nuitka[all] (>=4.1.3,<5.0.0)", 
  "zstandard (>=0.25.0,<0.26.0)", 
  "build (>=1.5.0,<2.0.0)", 
]

[project.scripts]
ivaldi = "ivaldi:main"
build = "ivaldi:build"
run = "ivaldi:run"
install = "ivaldi:install"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "ivaldi", from="." }, ]
include = []

[tool.coverage.run]
relative_files = true

[dependency-groups]
dev = [
    "ruff (>=0.16.0,<0.17.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "pytest-coverage (>=0.0,<0.1)",
]
