[project]
name = "ivaldi"
version = "0.1.7"
description = "Create a portable version of your Python Project"
authors = [
    {name = "Fionn Tolster"}
]
license = "MIT"
readme = "README.md"
requires-python = ">3.13,<3.15"
dependencies = [
  "requests (>=2.34.2,<3.0.0)", 
  "poetry[all] (>=2.4.1,<3.0.0)", 
  "nuitka[all] (>=4.1.3,<5.0.0)", 
  "zstandard (>=0.25.0,<0.26.0)", 
  "build (>=1.5.0,<2.0.0)",
]

[project.scripts]
ivaldi = "ivaldi:main"
build = "ivaldi:build"
run = "ivaldi:run"
install = "ivaldi:install"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "ivaldi", from="." }, ]
include = []

[tool.nuitka]
project = true
# Build flags
mode = "onefile"
no-prefer-source-code = true
assume-yes-for-downloads = true
output-dir = "dist/"
remove-output = true
static-libpython = "no"
onefile-no-compression = true

nofollow-import-to = ["*.tests", "tests", "*.benchmarks", "_decimal"]
enable-plugin = []
include-package = []

# OS compatability
include-windows-runtime-dlls = "yes"
company-name = "Neo4j"
product-name = "Ivaldi Installer"
file-description = "Creates a portable executable version of your project"

# # Runtime optimisations
# onefile-cache-mode = "cached"


[tool.coverage.run]
relative_files = true

[dependency-groups]
dev = [
    "ruff (>=0.16.0,<0.17.0)",
    "pytest (>=9.0.2,<10.0.0)",
]
